http:
  routers:
    nomes-www-http:
      entryPoints:
        - web
      rule: Host(`www.nomes.ro`)
      middlewares:
        - redirect-to-https
      service: noop@internal

    nomes-www-https:
      entryPoints:
        - websecure
      rule: Host(`www.nomes.ro`)
      service: nomes-app
      tls:
        certResolver: letsencrypt

    nomes-apex-http:
      entryPoints:
        - web
      rule: Host(`nomes.ro`)
      middlewares:
        - redirect-to-https-www
      service: noop@internal

    nomes-apex-https:
      entryPoints:
        - websecure
      rule: Host(`nomes.ro`)
      middlewares:
        - redirect-to-www
      service: noop@internal
      tls:
        certResolver: letsencrypt

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    redirect-to-www:
      redirectRegex:
        regex: ^https://nomes\.ro/(.*)
        replacement: https://www.nomes.ro/$1
        permanent: true

    redirect-to-https-www:
      redirectRegex:
        regex: ^http://nomes\.ro/(.*)
        replacement: https://www.nomes.ro/$1
        permanent: true

  services:
    nomes-app:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://nomes-app:3000
