export interface ArticleListing {
  id: number
  category: string
  title: string
  date: string
  readTime: string
  href?: string
}

export const articleCategories: string[] = [
  'Performance Ads',
  'Social Media',
  'Brand Strategy',
  'Video & Content',
  'Tutoriale',
  'Studii de caz',
]

export const articleListings: ArticleListing[] = [
  {
    id: 1,
    category: 'Social Media',
    title: 'Cum construiești un calendar editorial pentru social media în 2026',
    date: '07 IUN 2026',
    readTime: '9 MIN',
    href: '/articole/cum-construiesti-un-calendar-editorial-pentru-social-media-in-2026',
  },
  {
    id: 2,
    category: 'Brand Strategy',
    title: 'Ce este brand positioning și cum îți diferențiezi afacerea de competiție',
    date: '13 IUL 2026',
    readTime: '9 MIN',
    href: '/articole/ce-este-brand-positioning-si-cum-iti-diferentiezi-afacerea-de-competitie',
  },
  {
    id: 3,
    category: 'Video & Content',
    title: 'Reels vs TikTok vs YouTube Shorts: ce format video alegi în 2026',
    date: '14 MAI 2026',
    readTime: '10 MIN',
    href: '/articole/reels-vs-tiktok-vs-youtube-shorts-ce-format-video-alegi-in-2026',
  },
  {
    id: 4,
    category: 'Tutoriale',
    title: 'Cum instalezi Meta Pixel și Conversions API (și de ce e esențial)',
    date: '20 MAI 2026',
    readTime: '9 MIN',
    href: '/articole/cum-instalezi-meta-pixel-si-conversions-api',
  },
  {
    id: 5,
    category: 'Studii de caz',
    title: 'Cum alegi o agenție de marketing digital în România: 9 întrebări esențiale',
    date: '23 MAI 2026',
    readTime: '8 MIN',
    href: '/articole/cum-alegi-o-agentie-de-marketing-digital-in-romania-9-intrebari',
  },
  {
    id: 6,
    category: 'Performance Ads',
    title: 'Cât costă publicitatea pe Facebook și Instagram în România în 2026',
    date: '26 IUN 2026',
    readTime: '9 MIN',
    href: '/articole/cat-costa-publicitatea-pe-facebook-si-instagram-in-romania-in-2026',
  },
  {
    id: 7,
    category: 'Brand Strategy',
    title: 'Tone of voice: cum definești tonul vocii brandului tău (cu exemple)',
    date: '10 IUL 2026',
    readTime: '8 MIN',
    href: '/articole/tone-of-voice-cum-definesti-tonul-vocii-brandului-tau',
  },
  {
    id: 8,
    category: 'Brand Strategy',
    title: 'Identitate vizuală: cum construiești un sistem coerent de logo, culori și tipografie',
    date: '06 IUL 2026',
    readTime: '8 MIN',
    href: '/articole/identitate-vizuala-logo-culori-si-tipografie-coerente',
  },
  {
    id: 9,
    category: 'Brand Strategy',
    title: 'Rebranding: când are sens și când e doar bani aruncați',
    date: '02 IUL 2026',
    readTime: '8 MIN',
    href: '/articole/rebranding-cand-are-sens-si-cand-e-doar-bani-aruncati',
  },
  {
    id: 10,
    category: 'Brand Strategy',
    title: 'Brand storytelling: cum spui povestea brandului tău ca să vândă',
    date: '29 IUN 2026',
    readTime: '8 MIN',
    href: '/articole/brand-storytelling-cum-spui-povestea-brandului-tau-ca-sa-vanda',
  },
  {
    id: 11,
    category: 'Performance Ads',
    title: 'Ce este ROAS și cum îl calculezi corect pentru campaniile tale',
    date: '23 IUN 2026',
    readTime: '8 MIN',
    href: '/articole/ce-este-roas-si-cum-il-calculezi-corect-pentru-campaniile-tale',
  },
  {
    id: 12,
    category: 'Performance Ads',
    title: 'Performance Max în Google Ads: ghidul complet pentru magazine online',
    date: '19 IUN 2026',
    readTime: '10 MIN',
    href: '/articole/performance-max-in-google-ads-ghidul-complet-pentru-magazine-online',
  },
  {
    id: 13,
    category: 'Performance Ads',
    title: 'Funnel complet pe Meta Ads: TOFU, MOFU și BOFU explicate simplu',
    date: '16 IUN 2026',
    readTime: '9 MIN',
    href: '/articole/funnel-complet-pe-meta-ads-tofu-mofu-si-bofu-explicate-simplu',
  },
  {
    id: 14,
    category: 'Performance Ads',
    title: 'Retargeting pe Meta: cum recuperezi vizitatorii care n-au cumpărat',
    date: '13 IUN 2026',
    readTime: '8 MIN',
    href: '/articole/retargeting-pe-meta-cum-recuperezi-vizitatorii-care-nu-au-cumparat',
  },
  {
    id: 15,
    category: 'Performance Ads',
    title: 'Quality Score în Google Ads: ce este și cum îl crești ca să plătești mai puțin',
    date: '10 IUN 2026',
    readTime: '9 MIN',
    href: '/articole/quality-score-in-google-ads-ce-este-si-cum-il-cresti',
  },
  {
    id: 16,
    category: 'Social Media',
    title: 'Câte postări pe săptămână ai nevoie pe Instagram, TikTok și Facebook',
    date: '04 IUN 2026',
    readTime: '8 MIN',
    href: '/articole/cate-postari-pe-saptamana-ai-nevoie-pe-instagram-tiktok-si-facebook',
  },
  {
    id: 17,
    category: 'Social Media',
    title: 'Cum crești organic pe TikTok în 2026: ce premiază cu adevărat algoritmul',
    date: '01 IUN 2026',
    readTime: '9 MIN',
    href: '/articole/cum-cresti-organic-pe-tiktok-in-2026-ce-premiaza-algoritmul',
  },
  {
    id: 18,
    category: 'Social Media',
    title: 'Community management: cum răspunzi la comentarii, DM-uri și review-uri negative',
    date: '29 MAI 2026',
    readTime: '8 MIN',
    href: '/articole/community-management-cum-raspunzi-la-comentarii-dm-uri-si-review-uri-negative',
  },
  {
    id: 19,
    category: 'Social Media',
    title: 'Mai contează hashtag-urile în 2026? Ce funcționează acum și ce nu',
    date: '26 MAI 2026',
    readTime: '7 MIN',
    href: '/articole/mai-conteaza-hashtag-urile-in-2026-ce-functioneaza-acum',
  },
  {
    id: 20,
    category: 'Tutoriale',
    title: 'Google Analytics 4 pentru începători: metricile care contează cu adevărat',
    date: '17 MAI 2026',
    readTime: '9 MIN',
    href: '/articole/google-analytics-4-pentru-incepatori-metricile-care-conteaza',
  },
  {
    id: 21,
    category: 'Video & Content',
    title: 'UGC (User Generated Content): ce este și cum crește vânzările',
    date: '11 MAI 2026',
    readTime: '8 MIN',
    href: '/articole/ugc-ce-este-user-generated-content-si-cum-creste-vanzarile',
  },
  {
    id: 22,
    category: 'Video & Content',
    title: 'Cum scrii scriptul unui reel care convertește',
    date: '08 MAI 2026',
    readTime: '8 MIN',
    href: '/articole/cum-scrii-scriptul-unui-reel-care-converteste',
  },
]
